### PR TITLE
Wrote in Labels.rst

### PR DESCRIPTION
**Pull request by The5heepDev**
This can be added on, but I think I covered most of what labels are (for strings).

### CODE REVIEW

**Comment by ez80** [comment]
Thanks!

**Comment by The5heepDev** [comment]
Btw when will the git be pushed to the site?

**Comment by ez80** [comment]
Sorry, I was going to edit the other comment with this info before, but there's no edit button so I didn't. 
I think RTFD's auto-update might be broken, so I'll investigate and manually push it shortly.

**Comment by The5heepDev** [comment]
Sweet

**Comment by ez80** [comment]
Yep, turns out RTFD is having "internal issues" :/
Manual fix incoming

**Pull request merged**
